# Generated by Django 4.1.1 on 2022-10-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Regno', models.IntegerField()),
                ('EmailID', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
    
    

