# Generated by Django 4.1.1 on 2022-10-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Regno', models.IntegerField()),
                ('Subject', models.CharField(max_length=250)),
                ('Mark', models.IntegerField()),
                ('Grade', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mark',
            },
        ),
    ]
